################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - ./gradlew build sonarqube -Dsonar.host.url=$SONAR_URL -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.login=$SONAR_TOKEN

##################
### Deployment ###
##################
deploy:
  provider: script
  script: ./gradlew jar publish
  on:
    tags: true

###################
### Environment ###
###################
env:
  global:
    - SONAR_URL=https://sonar.klauke-enterprises.com
    - SONAR_PROJECT_KEY=cathedra
    - secure: lr1/zGlnEnG1PUNpjBhTxTQ1hSsLuQH0JcsA/W1a6RNtpTAYJtXHC4dxWKKz+lSrraUY7shhLUFuIcz5aG2EcZOWyq7WR6yDqWWiLpZnlDfIqndCAIgC4S1oMHHMJ7UGDexrwfr7XwbWq3ArzJHFhVsHQc553gVw/njBnfs/8HvUo+Amix4NFg5jyfXcbAoewA9tywaAeAc9mu291Fc0Q4pj+SK+Y8LusRTSJBe1I5gnfHGFQG708BEm05/uBdeka0tphgOX8jh5pHTIxD/o4ZieCB77qRbYum9fRdG6WhamxS+Y20IcdIZ1arRUqBkb/2wpkVNNMvK52YOKG5LS56lW+nKStPyZYADT0y9Uq2DW+Qwdl+6OBnWJCAM9+fxNJJQLLy3rAc1XmNmRdyXOdB9nw4owI60Oa5cVtphsVL0r8bqusHSqSpHraSRT5IerjIIwTlYk3T7F45Tx8ZJz5S3ZxO58oFwFVHCjb/lm5lQeHgtZYuRsEL1WhqgEXAiKDWPntZSKTTA8nvAthnUsE0kTv3AfF+ZSR/MF+0W6QHQEap1QICz6qda7VmcZmt9FFeNAJTBa8Vg90e45OhSsXVdqdtU1Vdr4Ay3Wml97Q2r3v5IpdVYEQj8DaKjGTCh/lwP4kHpvrf84Owt8kD9HYxzuQaO0axSTqAc4lRdrd8U=
    - secure: MDrDtW2hCRiJvGyKbFQZBUOgR2I59xaYn7o99bG/zoL8Gl3NLPVv4amLyaYHU59wwrg/brhfZKGqpvuWsQpz9uKc+Lt86iA/JyYc6LniN0UrbGsikeydCY5fr5xHNl4M34unhHwjVIEXaGXhUcJMcSk57x1XGvBlg32QgYed7GgN1npzusrg338VdJ6x1hsQiZsPaE8D9LAagRpJILZOzp12iQAvh+yjc8WDHywgdB2ftscBYXKih6RoEfrTwzzbg1k3T7Cii0Vy392927pDV6h+tVbDezaDgOw8Ggwp8mUo+kusgqYq5M69MnVq9eRhALlc9ZBZHCe59iyMCX5pkLMgIte914eY0UgW1B4wZkp9NG/XwGWdMIHHs3ULYdAY5HahFbHDwUMDZU+FQL+1tcs8EO8xVMBfr4FYRAbhRTloDUcwqWs3u6wOG3PUTpt/7hsn4j2GRRKTkkOe4D0+QlkVnje94k3Ojncy+7S8+zuxS8neX13HyS/AuFaSf1EBSyDIx/YKFCwVHHzow/EuNDJEeeYzTizp8SeU0TfLAzC6X3HUPj3GMI/4bOxwVZNXJzyKEItvr3NXIBIFcVNGP3Yp4RNSsGiuVLQU/tkKpT/FzyMZNhzx7C9YaTmCDJM67iKG4fXIbZ8xFBERi3CnBiD8Dvu+gqxy4ScmjvEEtfY=
    - secure: mqx0Bw7tLyCGtk6LQqnwUKNPBTiZtoPXPZjP5gQBO+kGeEkdmy/Vud8kdXMSMkGGHieeotBLXBh0gBWN8uB465f33UNqzeRjUDIlmj5IWjsuxyuO90Nnbfzu7ELoiAhebU2cwSBBOL1qRiNgqoWKFWY6gLn7qly8He2B3uagEpzkYVXimvTMmSW5kpGvTLbHUVv3IwqV9frrpyBWgSPVogDUtrW9MrQwbyhbh7wKLKETK48nyTaLLiaLbzisAMsTr55D2WSLq7jfoN59uTvHv6VmkIR5UxDPcESoKFcMyUQXFwx54zh0XDwoSFPjeQlti8B7HpEfphBygdCb5QxJRkH/aQ30eE9j83TNdqHQzScwDtyrpneF9Yq2aEMwW+H4fvzC6Tjy6j3nxOuFic39d1NjMnkB5AnbVfa7XHzZGqXTmH5o1S+5NMdk+oyEXCL36hQps7kRH+kI+jj3sYQLHlwFw93xDzlTZmaam+PqxmlmgPVODH/aanOVzob/6tc43MLc7AfRoNX7gXMjWawbpTD9H7cx+tIiYLvRlcnKOzB8K3acko0Jfy0/9PTRasXyMzSDdOe7vBFO/msJlbJD++khBxMOxMCCv5aU3cexx1pON+PtwkxyfiWo1RERXP1tNdT6xEZ8VjPOEGyJrW+2V+KlFIQGwmdq9BGg11eeMwA=
